name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Install CMake and GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++


    - name: Clean build directory
      run: rm -rf build


    - name: Configure CMake
      run: cmake -S . -B build


    - name: Build with CMake
      run: cmake --build build


    - name: Check directory permissions
      run: ls -l
